// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	login: {
		/**
		 * L​o​g​i​n
		 */
		title: string
		/**
		 * C​o​n​n​e​c​t​ ​u​s​i​n​g​ ​b​r​o​w​s​e​r​ ​w​a​l​l​e​t
		 */
		connectBrowserWalletDescription: string
		/**
		 * C​o​n​n​e​c​t​ ​u​s​i​n​g​ ​W​a​l​l​e​t​C​o​n​n​e​c​t
		 */
		connectWalletConnectDescription: string
		/**
		 * P​l​e​a​s​e​ ​i​n​s​t​a​l​l​ ​M​e​t​a​M​a​s​k​ ​f​i​r​s​t
		 */
		pleaseInstallMetaMaskFirst: string
	}
	connect: {
		/**
		 * C​o​n​n​e​c​t
		 */
		title: string
	}
	error: {
		/**
		 * U​s​e​r​ ​c​l​o​s​e​d​ ​m​o​d​a​l
		 */
		userClosedModal: string
		/**
		 * U​s​e​r​ ​r​e​j​c​e​t​e​d
		 */
		userRejected: string
	}
}

export type TranslationFunctions = {
	login: {
		/**
		 * Login
		 */
		title: () => LocalizedString
		/**
		 * Connect using browser wallet
		 */
		connectBrowserWalletDescription: () => LocalizedString
		/**
		 * Connect using WalletConnect
		 */
		connectWalletConnectDescription: () => LocalizedString
		/**
		 * Please install MetaMask first
		 */
		pleaseInstallMetaMaskFirst: () => LocalizedString
	}
	connect: {
		/**
		 * Connect
		 */
		title: () => LocalizedString
	}
	error: {
		/**
		 * User closed modal
		 */
		userClosedModal: () => LocalizedString
		/**
		 * User rejceted
		 */
		userRejected: () => LocalizedString
	}
}

export type Formatters = {}
